language: node_js

node_js:
  - "stable"

install:
  - npm install

script: 
  - npm test

after_success: npm run coverage

notifications:
  email: false
  
services:
  - mongodb

deploy:
  provider: script