language: node_js

node_js:
  - "stable"

install:
  - npm install

script: 
  - npm test

after_success: npm run 

cache:
  directories:
    - 'node_modules'
  yarn: true

notifications:
  email: false
  
services:
  - mongodb

deploy:
  provider: script